### ISSUE TITLE
Rvx-builder 5.0.4 Revanced apk corrupted and unsigned

### ISSUE THREAD

**Issue by lowestprime** [YT-Advanced/YT-Advanced#100]
Seem like the apk is not signed 🤔

_Originally posted by @YT-Advanced in https://github.com/YT-Advanced/YT-Advanced/issues/97#issuecomment-1698453941_
 
Still fails despite "./rvx-builder.sh reinstall --delete-keystore"

![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/99fb9210-aac8-4f05-9f61-213925bfb1f5)

![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/ea7843d6-f8bd-43d0-9752-8c0b9748b0f8)

**Comment by lowestprime** [comment]
Update 8/30/23:
Attempted to manually sign the apk using Apktool M, but this failed so I don't think the issue is with apk signing but rather compiling: 
"Signature (V1 + V2 + V3 + V4) failed!" and "Malformed APK: not a ZIP archive"

![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/1b6dcdac-04e7-4ca5-903b-793ec42faa36)

**Comment by lowestprime** [comment]
Confirmed that ReVanced Manager latest version patches the app perfectly, including the final compiling and signing steps. This is definitely a rvx-builder-specific issue. 

[revanced-manager_patcher_20230830190030815285.log](https://github.com/YT-Advanced/YT-Advanced/files/12481474/revanced-manager_patcher_20230830190030815285.log)

![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/2ad176fd-11a2-4d10-93f8-fe95de21847a)

**Comment by lowestprime** [comment]
Unfortunately, the latest rahulkhatri137 and j-hc revanced-clis still do not fix this:
https://github.com/rahulkhatri137/revanced-cli/releases/tag/v3.1.0-dev
https://github.com/j-hc/revanced-cli/releases/tag/v3.1.0

**Comment by YT-Advanced** [comment]
Can u check the builder again ?

**Comment by lowestprime** [comment]
Initially, after updating to 5.1.0 (./rvx-builder.sh update && ./rvx-builder.sh run), rvx-builder got stuck on "copying to..."
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/eb1591ac-58ad-4041-9833-7ba8eee498b6)

But then, after issuing the reinstall command, "./rvx-builder.sh reinstall && ./rvx-builder.sh run", rvx-builder ran and patched perfectly, including the final compilation/signing steps.
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/89955de7-f10d-4a8c-a85e-70820dfcdf34)

![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/85fa714c-9ad6-4e0b-8223-d77c532f6578)

**Comment by lowestprime** [comment]
The only issue now is having to reinstall everything, given the apk signature mismatch. It's not an issue for ReVanced, using its settings import/export feature; but for Reddit, it will require manually changing the settings in the reinstalled app. This could be solved in a future build by: 

1. Leveraging the newest revanced-cli ver's support for unsigned apk signature toggle to add a signature option to the settings page of rvx-builder.
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/aa594938-cd61-4b1c-bda2-2a0775a70b96)
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/e52ead55-1579-4e8d-9b1a-d22b3e922e07)
https://github.com/rahulkhatri137/revanced-cli/commit/891750420f4a9444d38bd8cee97c94ec0ae13cb6
And/or

2. Allow keystore (for patches would be great too) import/export/copy from existing apk options like in ReVanced Manager.
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/18ddf85d-b199-4655-810a-46ae3571b2e8)

I will close and make new suggestion.
