### ISSUE TITLE
Rvx-builder 5.0.4  EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by 123jjck** [YT-Advanced/YT-Advanced#103]
When patching YouTube with the latest version of RVX Builder, an error occurs every time:
```
[builder] An error occured:
Error: EBUSY: resource busy or locked, rename 'C:\Users\Admin\Downloads\revanced\revanced.apk' -> 'C:\Users\Admin\Downloads\revanced\ReVanced-cli_v3.0.1-patches_v2.189.1.apk'
at renameSync (node:fs:1038:3)
at afterBuild (C:\snapshot\rvx-builder\wsEvents\patchApp.js:36:3)
at Socket. (C:\snapshot\rvx-builder\wsEvents\patchApp.js:187:55)
at Socket.emit (node:events:537:28)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:297:9)
at Readable.push (node:internal/streams/readable:234:10)
at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
Please report this bug here: https://github.com/YT-Advanced/rvx-builder/issues.
```
Tried rebooting the PC, deleting all RVX-Builder files and trying again, nothing helped
The revanced.apk file seems to be corrupted and won't install

**Comment by YT-Advanced** [comment]
It is know bug from CLI, for some unknown reason it didn't finish the work. You should use another way to build right now

**Comment by YT-Advanced** [comment]
Fixed in rvx-builder v5.1.0

**Comment by ezeraiser** [comment]
Sadly, stuck here... Doesn't work v.5.1.0
![image](https://github.com/YT-Advanced/YT-Advanced/assets/133262526/48c0a80d-1df9-4e73-ba8d-96cd0a6b0ac1)

**Comment by YT-Advanced** [comment]
@ezeraiser Open the setting and set to be like this:
![image](https://github.com/YT-Advanced/YT-Advanced/assets/70064328/ceda722c-33bb-495a-8510-1dcdaf325501)

**Comment by yuukiAme** [comment]
> @ezeraiser Open the setting and set to be like this: ![image](https://user-images.githubusercontent.com/70064328/265014650-ceda722c-33bb-495a-8510-1dcdaf325501.png)

Yes. I did it. I changed the Settings to **YT-Advanced** and built with RVX-builder 5.1.0. It works perfectly.


![2023-09-02 08_03_37-Window](https://github.com/YT-Advanced/YT-Advanced/assets/45681604/537df064-1029-431f-97ec-c111dace3211)
