### ISSUE TITLE
Export/import Sponsorblock settings 

### ISSUE THREAD

**Issue by Johny2074** [YT-Advanced/YT-Advanced#105]
Is there possibility to export and import Sponsorblock settings especially these settings
For example, 
![Screenshot_20230831_141146_app rvx android youtube_edit_467894747603603](https://github.com/YT-Advanced/YT-Advanced/assets/142300200/438cb271-57c5-4528-a554-0e446e36dbd0)
It is set to be Skipped automatically. Every time i have clean install new version of YouTube i have to set all of them as "show skip button" 
So if there as an import and export feature of Sponsorblock settings it would be great 
Thank you in advance.

**Comment by YT-Advanced** [comment]
It already have, scroll down and you will see it
