### ISSUE TITLE
Crowdin translation doesn't match

### ISSUE THREAD

**Issue by Kuddus73** [YT-Advanced/YT-Advanced#106]
This is what is shown in app:
![Screenshot_20230901_093506_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/127908708/5b906183-7be7-4b3e-8c70-fc97eedadb1f)

This is the translation on Crowdin:
![Screenshot_20230901_093810_Chrome Beta](https://github.com/YT-Advanced/YT-Advanced/assets/127908708/f0744c69-b84f-4577-a91d-afed00595da7)
Note: the translation was submitted and approved before the release of the update so it should match.

**Comment by YT-Advanced** [comment]
It is my plan, not bug

**Comment by Kuddus73** [comment]
> It is my plan, not bug

Plan?
What do you mean?

**Comment by YT-Advanced** [comment]
> > It is my plan, not bug
> 
> Plan? What do you mean?

Because we don't have enough translation for the new string so I plan to push it in next update
