### ISSUE TITLE
Request: Dislikes on YouTube Music

### ISSUE THREAD

**Issue by PikaGamer8** [YT-Advanced/YT-Advanced#108]
Now that YouTube added likes and comments on YouTube Music, I suggest that if possible, we should also be able to see dislikes on all songs.

Thanks for your work. 😊

![Screenshot_20230901_135611_ReVanced Extended Music](https://github.com/YT-Advanced/YT-Advanced/assets/77557847/72a916c4-e743-42ef-8d57-50352fe255a8)

**Comment by YT-Advanced** [comment]
Added in lastest version

**Comment by AdishSagarawat** [comment]
@YT-Advanced You can unpin this issue then 😅
