### ISSUE TITLE
Hide captions layout footer

### ISSUE THREAD

**Issue by federicogith** [YT-Advanced/YT-Advanced#111]
It is really similar to your recently added "hide quality layout footer" (https://github.com/YT-Advanced/ReX-patches/pull/20) feature but for captions.
![ _20230901_225926](https://github.com/YT-Advanced/YT-Advanced/assets/130296934/cc8c97d5-ffa1-4da2-9c3a-5f575fd4c648)

**Comment by YT-Advanced** [comment]
Added in lastest version
