### ISSUE TITLE
Hide Remix Button in Shorts is not working in RVX Patches v2.190.1

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/YT-Advanced#119]
![Screenshot_2023-09-05-17-12-21-70_d11ae654701a5fadb313ea6fa9a6836f.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/91815107/b2195b59-1ecc-4d4a-82a0-0520967eb4dd)

![Screenshot_2023-09-05-17-11-58-65_d11ae654701a5fadb313ea6fa9a6836f.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/91815107/0928452e-5d62-4606-952c-fbfd93f588b1)

**Comment by YT-Advanced** [comment]
Wait, it is not Remix Button. It is Shorts Pivot Button lol
