### ISSUE TITLE
Youtube short crash issue

### ISSUE THREAD

**Issue by Adity1243** [YT-Advanced/YT-Advanced#12]
The app crashes if i touch youtube shorts videos.

**Comment by YT-Advanced** [comment]
Can you share a video ?

**Comment by Adity1243** [comment]
Sure,
https://drive.google.com/file/d/19pptp06OotPEyeIcWrkR674pblkANIMO/view?usp=drivesdk
Even if i exclude all that options from shorts from youtube its still crashing.

**Comment by YT-Advanced** [comment]
@Adity1243 Can you try repatch with my newest patch (I recently updated it) and perform a clean install

**Comment by Adity1243** [comment]
OK it got fixed thanks.
