### ISSUE TITLE
Enable "Play Next in Queue" feature, if possible.

### ISSUE THREAD

**Issue by AdishSagarawat** [YT-Advanced/YT-Advanced#120]
Currently, it says to buy YouTube Premium...

![Screenshot_20230905-200748_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/69076256/7952fbbe-1086-46b9-ac76-30694391be81)

Thanks!

**Comment by YT-Advanced** [comment]
It is a server-side feature, and I'm not Youtube employer so I can't modify it :D
