### ISSUE TITLE
Fix Ambient Mode and Seekbar Thumbnails for Player Parameters of Incognito Mode.

### ISSUE THREAD

**Issue by LegendarySpinx** [YT-Advanced/YT-Advanced#121]
Seekbar Thumbnails is a useful thing and it annoys a lot to forward a without without any thumbnail preview...

![Screenshot_20230905-200812_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/69076256/2fd46eeb-883a-446a-acc4-e644204555c5)

**Comment by AdishSagarawat** [comment]
@YT-Advanced ig Inotia has fixed some issues in latest update of patches, please merge then to rex as well


Thanks 😃

**Comment by YT-Advanced** [comment]
I see, also I'm implement seekbar thumbnails
