### ISSUE TITLE
Add in-built Downloader Support from the default Download Button

### ISSUE THREAD

**Issue by AdishSagarawat** [YT-Advanced/YT-Advanced#122]
With options like Video and Audio Quality,

Can use ;
1. https://github.com/yt-dlp/yt-dlp
2. https://github.com/JunkFood02/Seal

**Comment by Aryan-Chauhan** [comment]
It's already available.

Overlay Button > External downloader settings > Enable hook download button.

**Comment by YT-Advanced** [comment]
It already have this option, but worked only for Premium account
