### ISSUE TITLE
About ReX fixes and new features 

### ISSUE THREAD

**Issue by Johny2074** [YT-Advanced/YT-Advanced#125]
Hi 
Inotia had returned but he said that there is no more new feature for YouTube until some time 
So please can you push PR of your fixes like default video quality fix and other fixes 
And your new features to be incorporated to RVX

**Comment by YT-Advanced** [comment]
<img width="369" alt="image" src="https://github.com/YT-Advanced/YT-Advanced/assets/70064328/0aeffac5-3e28-4192-9419-16a3f1ba7ff3">

**Comment by Mohammed1520** [comment]
No need for that
If you will continue maintaining YouTube even if one updated every month including version update and minimal fixes this will be great
