### ISSUE TITLE
YouTUbe Search not working on single click

### ISSUE THREAD

**Issue by AdishSagarawat** [YT-Advanced/YT-Advanced#127]
Keyboard is not appearing on single click upon the search bar it requires double click (sometimes triple click as well)...

**Comment by SunSea88** [comment]
Hello,

Yes, it's also the same for me as I mentioned [there](https://github.com/YT-Advanced/YT-Advanced/issues/117)
The keyboard never appears by default, you have to press several times to get it in the YouTube Search :-(

**Comment by Adity1243** [comment]
It is ui lag just sam as laggy scrooling maybe youtube bug.

**Comment by Adity1243** [comment]
Reproducible in my device too the cause is ui is lagging but my issue is not search option related.
Solution :- try patching youtube v18.36.38 which is unsupported version, but working,only remove ambient mode restriction patch is fail, you can try its ui is smooth will fix your issue.

> Keyboard is not appearing on single click upon the search bar it requires double click (sometimes triple click as well)...

**Comment by YT-Advanced** [comment]
Hmm, if v18.36.38 worked, it mean it is Youtube bug 🫠

**Comment by Adity1243** [comment]
Yes ofc its is official youtube bug.
