### ISSUE TITLE
Hide Search Bar in Home Feed

### ISSUE THREAD

**Issue by ZeroZero0011** [YT-Advanced/YT-Advanced#128]
![Screenshot_20230908-150927_ReVanced Extended~01](https://github.com/YT-Advanced/YT-Advanced/assets/132404645/2b30b9b9-aefa-4dc8-9003-a60696bb72cf)

**Comment by YT-Advanced** [comment]
Turn on Search History and done

**Comment by StradivariusKane** [comment]
@YT-Advanced 

You can also hide it by enabling tablet mode, it would be cool if there was a feature that would spoof home tab believing tablet mode is enabled.

**Comment by ZeroZero0011** [comment]
@StradivariusKane 

Turning on search history didn't hide it. 
it is an A/B test.

**Comment by StradivariusKane** [comment]
> @StradivariusKane
> 
> Turning on search history didn't hide it. It is an A/B test on phone?

Turning on tablet mode will hide it, you can use it until there is a another solution.

You can find tablet mode in the RVX > Misc if you patched that in.

**Comment by ZeroZero0011** [comment]
@StradivariusKane 

I know, I don't want to use it in tablet mode because of the small thumbnails.
Thanks though.

**Comment by StradivariusKane** [comment]
> @StradivariusKane
> 
> I know, I don't want to use it in tablet mode because of the small thumbnails. Thanks though.

Understandable, the only reason why I dont like it is that video title becomes unhidable.

Maybe someday there will be a spoof patch for home tab that makes it think that tablet mode is enabled when its disabled.

**Comment by ZeroZero0011** [comment]
@StradivariusKane 

Today that search bar disappeared.
But I think shorts shelf is disappeared too.
I don't know if it's normal to have a search bar or not.
