### ISSUE TITLE
Request: a much elevated/ higher fullscreen seekbar height patch please.

### ISSUE THREAD

**Issue by Kantotero** [YT-Advanced/YT-Advanced#130]
it's already been re-added on the newest patch but could you revamp the `higher-fullscreen-seekbar-height` patch into much higher level? Particularly when disabling the `hide fullscreen panels` & also disabling the `hide quick actions container` please.

![Screenshot_2023-09-12-06-09-33-815.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/125627064/af33368e-7887-4800-a4dc-e0db77b3ae13)
This is the regular `higher-fullscreen-seekbar-height` without the `hide quick actions container` patch

![Screenshot_2023-09-12-06-28-31-399.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/125627064/d97cd638-9593-4bf9-b108-f9e11da6bb58)
Meanwhile this is the `higher seekbar height
` with quick action button. I want you to make it high like this height please while maintaining the `hide quick actions container` disabled also.

**Comment by StradivariusKane** [comment]
I confirm.

**Comment by YT-Advanced** [comment]
Can confirm, will readd it

**Comment by Kantotero** [comment]
> Can confirm, will readd it

I kindly request a `higher fullscreen seekbar height` patch please. Please refer to my edited post.
