### ISSUE TITLE
Hide quality menu footer not working on YT v18.35.35

### ISSUE THREAD

**Issue by Kantotero** [YT-Advanced/YT-Advanced#131]
![IMG_20230909_215041.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/125627064/f3896546-e58b-4945-9461-8f7d801520ff)

The `hide quality menu footer` patch under flyout menu is not working for v18.35.35 with the latest patch release

**Comment by StradivariusKane** [comment]
#112 was reopened, can you close this issue.
