### ISSUE TITLE
Add option to whitelist ads in whitelist channels button.

### ISSUE THREAD

**Issue by AdishSagarawat** [YT-Advanced/YT-Advanced#133]
Currently, there is no such option to Whitelist channels for ads.

**Comment by YT-Advanced** [comment]
The only way you can do with Video Ads is repatch to get it showed, so cannot add option to whitelist ads
https://github.com/inotia00/ReVanced_Extended/issues/652

**Comment by YT-Advanced** [comment]
Hello I'm back to notify that it have been added

**Comment by AdishSagarawat** [comment]
Ok, nice then 

Thanks mate !
