### ISSUE TITLE
Suggestion: Change the description string (Hide notify me button)

### ISSUE THREAD

**Issue by YoghurtAndPizza** [YT-Advanced/YT-Advanced#14]
I saw that you implemented a patch to hide Notify me button, thank you for it. But I have one small suggestion for the string that you used:

![Screenshot_20230811_161345_ReVanced Extended](https://github.com/YT-Advanced/YT-Advanced/assets/141920927/add2839e-d29d-4630-a7cf-5fb2ef0a1a7a)

It says in the description "Notify me button are hidden", can you change it to this one:

Notify me button is hidden

Or alternatively to this one: 

Notify me buttons are hidden.

**Comment by YT-Advanced** [comment]
lmao, just add `s` :)))

**Comment by YoghurtAndPizza** [comment]
Yes lol.
