### ISSUE TITLE
feat(patch): option to hide add comment panel

### ISSUE THREAD

**Issue by ANewDawn** [YT-Advanced/YT-Advanced#140]
**Issue**
An option to hide the add comment panel in the comments section to free up some space.

![comment](https://github.com/YT-Advanced/YT-Advanced/assets/51456745/f8d51622-30bd-4466-ab5b-0c6cd7bb4e58)

**Motivation**
For users who browse YouTube without signing into an account the add comment won't be used. Option to hide it will be useful.

**Comment by YT-Advanced** [comment]
Add this ones to Custom Filter:
`composer_static`
