### ISSUE TITLE
Request: Option to hide Channel Intro Video

### ISSUE THREAD

**Issue by StradivariusKane** [YT-Advanced/YT-Advanced#141]
Just to make channels more appealing to enter, and to reduce clutter.

Channel that has intro video, cohhcarnage.

**Comment by YT-Advanced** [comment]
Include SponsorBlock

**Comment by StradivariusKane** [comment]
No, I meant this one:

![Screenshot_20230913_114402_ReVanced Extended](https://github.com/YT-Advanced/YT-Advanced/assets/144253206/a58d774d-77f1-4502-b058-c5f770124f12)

**Comment by YT-Advanced** [comment]
Ah, I see, but why u want to hide it 🥹

**Comment by StradivariusKane** [comment]
To make channels more clean.

**Comment by YT-Advanced** [comment]
Just skip it 🫠
