### ISSUE TITLE
bug:Hide captions menu footer doesn't work

### ISSUE THREAD

**Issue by Kuddus73** [YT-Advanced/YT-Advanced#142]
![Screenshot_20230912_140414_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/127908708/c7b3ae78-d167-4218-84e7-a308e7987f3d)
![ _20230912_140857](https://github.com/YT-Advanced/YT-Advanced/assets/127908708/61be7951-68f2-4065-a699-b87c2aec6bb4)
![Screenshot_20230912_140429_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/127908708/f8d3e20e-b85a-40fd-ac31-fb64b4616341)

**Comment by StradivariusKane** [comment]
Known issue, #112. Please close this issue.

**Comment by Kuddus73** [comment]
> Known issue, #112. Please close this issue.

I saw that you also discussed about my issue.
But that report's main issue is, as its tittle says, _quality_ footer, this one is about **captions** footer.

**Comment by Kuddus73** [comment]
@YT-Advanced I saw that you gonna release a last update for ReX.
Could you fix this bug before the release?

**Comment by YT-Advanced** [comment]
> @YT-Advanced I saw that you gonna release a last update for ReX.
> Could you fix this bug before the release?

I will, I think

**Comment by Aryan-Chauhan** [comment]
It's working perfectly fine for me.

**Comment by YT-Advanced** [comment]
For this problem, it only happen when you press the `CC` button

**Comment by Kuddus73** [comment]
Any update on this bug?

**Comment by YT-Advanced** [comment]
> Any update on this bug?

I think nope :((
