### ISSUE TITLE
Make the "Material You" patch more noticeable.

### ISSUE THREAD

**Issue by TeaOwO** [YT-Advanced/YT-Advanced#143]
There are some parts that don't have Material You:
![Screenshot_20230912-193101~2.png](https://github.com/YT-Advanced/YT-Advanced/assets/123305689/63c616df-b18b-4606-a2fb-98a5a7941e2b)

![Screenshot_20230912-192822~2.png](https://github.com/YT-Advanced/YT-Advanced/assets/123305689/59ee5553-29b9-4306-bef2-f589b0d4410d)

![Screenshot_20230912-193447~2.png](https://github.com/YT-Advanced/YT-Advanced/assets/123305689/fd761e98-eb81-4268-9152-e39b0b1c7bb1)

![Screenshot_20230912-193753~2.png](https://github.com/YT-Advanced/YT-Advanced/assets/123305689/054f8504-75e8-4dd8-b45d-cdc74e9d13c5)

**Comment by YT-Advanced** [comment]
It is from server side so I can't change it
