### ISSUE TITLE
bug:Enable save playback speed

### ISSUE THREAD

**Issue by federicogith** [YT-Advanced/YT-Advanced#149]
![Screenshot_20230926_091636_exteraGram](https://github.com/YT-Advanced/YT-Advanced/assets/130296934/4ab4e5b5-681f-4677-b499-1835e8dfbc13)

**Comment by YT-Advanced** [comment]
Can you explain more

**Comment by federicogith** [comment]
> Can you explain more

![Screenshot_20230926_174026](https://github.com/YT-Advanced/YT-Advanced/assets/130296934/415a224b-f327-487b-9781-846296300476)

**Comment by YT-Advanced** [comment]
Wait, I can't remembered it lol
