### ISSUE TITLE
Download of patches/integrations fails due to Github ratelimiting?

### ISSUE THREAD

**Issue by lowestprime** [YT-Advanced/YT-Advanced#153]
rvx-builder v5.1.0 can't start due to Github ratelimiting at patches/integrations download step.

![Screenshot_20231016_234014_Chrome Dev](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/5a0fc29e-9977-44ba-a42c-d995e54b13c9)

**Comment by YT-Advanced** [comment]
First, ReX discontinued so you should switch back to rvx-builder instead
Second, Github have rate limit when user download too much, just check back later and the bug will be fixed
