### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by nochlab1** [YT-Advanced/YT-Advanced#154]
Hi i really liked speed patch you added but went to go build again and see your source isn't showing up in revancify.
Thanks

**Comment by YT-Advanced** [comment]
It is discontinued a long time ago. For Whitelist Speed patch and Whitelist SponsorBlock, you can open an issues to inotia repos

**Comment by nochlab1** [comment]
Ok thanks for the effort you put into it really appreciated it
