### ISSUE TITLE
split "hide category bar in feed" into home feed and subscriptions feed

### ISSUE THREAD

**Issue by federicogith** [YT-Advanced/YT-Advanced#17]
https://github.com/inotia00/ReVanced_Extended/issues/594
(The current option hides the category bar on both home and subscriptions feed, I just want to hide it on subscriptions)

**Comment by YT-Advanced** [comment]
@federicogith Hello, sorry for my late reply but Youtube have their setting to hide it, why you need another option to hide it ?
![image](https://github.com/YT-Advanced/YT-Advanced/assets/70064328/3957b808-5de6-4da9-b4dc-8bdbb5bdae75)

**Comment by YT-Advanced** [comment]
Sorry for my late reply. But the category bar used by Home, Subscription and Notification tab and it must be inject as first start. It mean if you hide, all of them will hide and if you show all will show. Currently I don't have any idea to seperate it.
