### ISSUE TITLE
Add Crowdin translations support

### ISSUE THREAD

**Issue by Kuddus73** [YT-Advanced/YT-Advanced#18]
Add the support of Crowdin translations for the new features added.

**Comment by User-noob2036876** [comment]
Or weblate.. Or with github..

**Comment by YT-Advanced** [comment]
Don't tag me lol. I will notify when I can, now fully of work :(

**Comment by YT-Advanced** [comment]
@User-noob2036876 @Kuddus73 I have public Crowdin Project right now
https://t.me/ReXgroups/4

**Comment by User-noob2036876** [comment]
> @User-noob2036876 @Kuddus73 I have public Crowdin Project right now
> https://t.me/ReXgroups/4

Can you give me proofreader authorization for Turkish?
Im Turkish languages last translator (erguntas1968)

**Comment by YT-Advanced** [comment]
> Can you give me proofreader authorization for Turkish?
Im Turkish languages last translator (erguntas1968)
I'm also proofreader on revanced_extended_eu project

Done
