### ISSUE TITLE
buffering issue

### ISSUE THREAD

**Issue by UntaDotMy** [YT-Advanced/YT-Advanced#19]
hi , i tested all of your debug apk , and the patches ,  buffering is still there , you know how to fix this ?

**Comment by YT-Advanced** [comment]
Open Setting --> Miscellaneous, then turn on Spoof Player Parameter Type
Note that you will not able to get seekbar thumbnail

**Comment by UntaDotMy** [comment]
can you make it on by default for next release of patch ?

**Comment by YT-Advanced** [comment]
> can you make it on by default for next release of patch ?


I can but somebody will ask: "Hey bro, why my thumbnail is not showing"

**Comment by UntaDotMy** [comment]
> 

can you teach me how to enable it on default ?  just using it for myself and maybe can help other too

**Comment by YT-Advanced** [comment]
> 
> can you teach me how to enable it on default ? just using it for myself and maybe can help other too

Only I can make it enable by default 😢 But you can manual enable it :D

**Comment by UntaDotMy** [comment]
> > can you teach me how to enable it on default ? just using it for myself and maybe can help other too
> 
> Only I can make it enable by default cry But you can manual enable it :D

tqsm !
