### ISSUE TITLE
Failed to patch using RVX Manager and Revancify

### ISSUE THREAD

**Issue by YoghurtAndPizza** [YT-Advanced/YT-Advanced#21]
I used inotia00's RVX Manager with YT-Advanced's sources, and I'm getting failed to apply errors. When I saw those errors I manually aborted patching.

![Screenshot_20230813_114859](https://github.com/YT-Advanced/YT-Advanced/assets/141920927/743dafe0-96ea-46ef-8ebf-a9cdd535eb4e)

**Comment by YoghurtAndPizza** [comment]
Same error with Revancify.

**Comment by YT-Advanced** [comment]
@YoghurtAndPizza You are patching unsupported version

**Comment by YoghurtAndPizza** [comment]
Wow, I just had a massive brain fart and accidentally selected the unsupported version.
