### ISSUE TITLE
hide join button in the channel information

### ISSUE THREAD

**Issue by federicogith** [YT-Advanced/YT-Advanced#22]
https://github.com/inotia00/ReVanced_Extended/issues/1177

**Comment by YT-Advanced** [comment]
You can hide it by adding `|button.eml` to Custom Filter

**Comment by federicogith** [comment]
Tried adding `|button.eml` to custom filter but it also hides buttons under the player.

So add an option to hide both the subscribe and join buttons in channel infomation.

**Comment by federicogith** [comment]
@YT-Advanced didn't get any answer back.
So can you add an option to hide both subscribe and join button?

**Comment by YT-Advanced** [comment]
> @YT-Advanced didn't get any answer back.
> So can you add an option to hide both subscribe and join button?

Yes, I will

**Comment by MrNorthernLights** [comment]
> @YT-Advanced didn't get any answer back. So can you add an option to hide both subscribe and join button?

Add this line in custom filter:

channel_action_button
