### ISSUE TITLE
hide full screen button

### ISSUE THREAD

**Issue by Kuddus73** [YT-Advanced/YT-Advanced#24]
![252736752-a005cf9d-1d68-45c6-ab01-89d1cbd84527](https://github.com/YT-Advanced/YT-Advanced/assets/127908708/f24709df-ea2b-450e-8200-398751e37dbc)

**Comment by YT-Advanced** [comment]
Wut ? Why you need to hide Full Screen Button ?

**Comment by Kuddus73** [comment]
You can just enter full screen by swiping up and get out by swiping down.
Also, some users never watch video on full screen.

**Comment by YT-Advanced** [comment]
It is the main feature of Youtube. Hide it will not necessary at all

**Comment by Kuddus73** [comment]
Also, I have the seekbar tapping option enabled and sometimes I mis-tap, instead of tapping the full screen button I tap the seekbar near it and it skips to the end of the video by mistake.

**Comment by YT-Advanced** [comment]
You can disable Seekbar Taping bro

**Comment by Kuddus73** [comment]
Yes, I know, of course, but I need seekbar tapping.
Hiding the full screen button would have solved the issue of skipping video by mistake.

If it's not possible to hide the button, thanks anyway.

**Comment by YT-Advanced** [comment]
> Yes, I know, of course, but I need seekbar tapping. Hiding the full screen button would have solved the issue of skipping video by mistake.
> 
> If it's not possible to hide the button, thanks anyway.

First, the full screen button is main feature of Youtube
Second, as you said, when you clicked the full screen button, it skip to the ends. You can stop using full screen button and swipe up to go to full screen mode as well
So I will not create a patch to hide it. Sorry about it :(

**Comment by Kuddus73** [comment]
> You can stop using full screen button and swipe up to go to full screen mode as well

That is exactly what I've been doing.
So for me it's completely useless seeing the full screen button.

But I understand you.

**Comment by YoghurtAndPizza** [comment]
You can also just rotate your phone to landscape and it will make videos fullscreen, I would also like to hide this button if possible. I love clean look.

![Screenshot_20230814_103507_YouTube Premium](https://github.com/YT-Advanced/YT-Advanced/assets/141920927/4d0cfb49-6e08-4a92-8c56-4c5acff9c1f3)

I would also love to hide play/pause button, but that's another patch request, it was requested before in inotia00.

**Comment by 1node00** [comment]
I would love to get this implemented, this fullscreen button stays visible at all times when watching vertical videos and doesn't go away. And it's the only button in the overlay that's visible. Can you please reconsider adding this patch?

**Comment by StradivariusKane** [comment]
Hiding fullscreen button would be useful when watching vertical videos where fullscreen button doesnt hide at all, it stays visible at all times in vertical videos.
