### ISSUE TITLE
Rvx builder related things

### ISSUE THREAD

**Issue by girshcatt** [YT-Advanced/YT-Advanced#26]
1.Create a fork of inotia's rvx builder guide and change all inotia00 in commands to YT-Advanced
2.Change for rvx builder repo in readme.md link to your rvx builder guide
3.And last i wanted to say that when you download dependencies in rvx builder, it downloads Vanced MicroG. This microg is not up to date, change rvx builder to download mmicrog instead of vanced microg

(P.S can you update mmicrog in future to latest OxrxL mMicroG 0.2.28.232512?)

Also change microg-support patch name to mmicrog-support and change this in patch description too

**Comment by girshcatt** [comment]
Thanks for answer anyway, i will wait as much as it will take

**Comment by YT-Advanced** [comment]
I have match all of them with my patch, hope it work :D
https://github.com/YT-Advanced/rvx-builder/releases/tag/v4.0.0

**Comment by girshcatt** [comment]
Thank you:)
