### ISSUE TITLE
Cosmetic bug with overlay-buttons

### ISSUE THREAD

**Issue by girshcatt** [YT-Advanced/YT-Advanced#27]
This bug will appear only in tablet ui, rvx also had this bug, this bug hard to explain, but i will try. When in tablet ui or just on tablet in player pause menu when video playing you will go to fullscreen mode all overlay buttons will appear on screen for ~second

https://github.com/YT-Advanced/YT-Advanced/assets/110785596/7aee0465-4792-45ad-b5ae-24150eaa2578

![257060558-43b1e1ee-c644-47a7-abbb-4792d6542379](https://github.com/YT-Advanced/YT-Advanced/assets/110785596/a2ee7f63-2072-47e7-bea7-531271c189a6)

**Comment by Adity1243** [comment]
Maybe your tablet animations are slow thats why its taking time to rotate and moving full screen player components.
 Solution :- 
1)go to developer option
2)Search window animation scale, transition animation scale, animator duration scale
3) set to .5x

**Comment by girshcatt** [comment]
I used all animtions in 0.5x all time

**Comment by Adity1243** [comment]
I tried tablet layout in phone and issue is not reproduced in my device maybe your tablet animation issue and this issue is not that much big.

**Comment by girshcatt** [comment]
Maybe this appear not on tablen ui, especially on tablet

**Comment by Adity1243** [comment]
> I used all animtions in 0.5x all time

Not 0.5x its slowest animation use .5x

**Comment by Adity1243** [comment]
> Maybe this appear not on tablen ui, especially on tablet

Thats i am saying

**Comment by girshcatt** [comment]
I will try and write after this

**Comment by girshcatt** [comment]
same issue with 5x animation

https://github.com/YT-Advanced/YT-Advanced/assets/110785596/4fdffaf5-dcde-47d6-b270-52de320db91f

**Comment by girshcatt** [comment]
![Screenshot_20230814_213244_Settings](https://github.com/YT-Advanced/YT-Advanced/assets/110785596/eb61dcf1-77c1-42d0-8f1d-175980b71783)

**Comment by Adity1243** [comment]
No bro its should start with  .5x

![Screenshot_2023-08-15-00-06-23-684_com android settings](https://github.com/YT-Advanced/YT-Advanced/assets/131557644/ca50c058-24b8-4b48-a61e-edd57eafbc07)

**Comment by Adity1243** [comment]
Then did you have 1x

**Comment by girshcatt** [comment]
I tried this bug in all speeds, speed cant be connected to this bug

**Comment by Adity1243** [comment]
Idk man

**Comment by Adity1243** [comment]
Tablet issue definitly

**Comment by girshcatt** [comment]
Anyway issue is issue, it need to be answered by developer, this is weird to think that this is tablet issue, bcause this is not ximi not 0.5 ultra pro, this is normal device with official rom

**Comment by girshcatt** [comment]
When patches get update i do clean install every time, i say even more that i do hard reset every 2 months, i think such issues go unnoticed because of not much tablet users

**Comment by YoghurtAndPizza** [comment]
Have you tried to change spoof app version target?

**Comment by girshcatt** [comment]
Yes, 3 months ago i used spoof on old versions, on all layout i got this bug

**Comment by YT-Advanced** [comment]
> Yes, 3 months ago i used spoof on old versions, on all layout i got this bug

It is know issues because tablet layout use different layout. And now I have no idea to solve it

**Comment by Adity1243** [comment]
> Yes, 3 months ago i used spoof on old versions, on all layout i got this bug

Did you exported your old settings revert it to latest version or disable spoof app version target and clear data of your youtube app and tell if issue got fix or not

**Comment by girshcatt** [comment]
If you didn't know that on major updates don't reccomended to copy your setting, after all updates i do all what i need manually. Trust me, i tried this bug at every parameter on every version, this is not issue that fixable just disabling any switch in settings or clean data

**Comment by Adity1243** [comment]
And you saying its rvx bug.

**Comment by YT-Advanced** [comment]
> And you saying its rvx bug. Did you tried official youtube did the bug is occuring .

It is a know issues. And offical Youtube don't have Overlay Button UwU

**Comment by Adity1243** [comment]
Sometime player button gets stuck the common issue of youtube i already reported by official feedback option nothing responce yet.

**Comment by AdishSagarawat** [comment]
Yes, facing the same issue on realme pad with stock rom.
It occurs only in landscape mode while video is playing
Everything is fine when video is paused in landscape mode.

**Comment by girshcatt** [comment]
Oh, i happy that i see someone with the same issue, bcause all people said that can't reproduce

**Comment by YT-Advanced** [comment]
Can u check it in latest version ?

**Comment by girshcatt** [comment]
> Can u check it in latest version ?

I will chack it when revancify will support your latest patch, cause i need different package name, i have installed rvx, i will reply when i will test
