### ISSUE TITLE
patch request: hide store tab

### ISSUE THREAD

**Issue by MondayNitro** [YT-Advanced/YT-Advanced#29]
please add a patch to hide "store tab", or maybe generalise the patch where user can type the tab name in a dialog box and restart app to hide that particular tab. thanks!

![photo_6260048467988691265_y](https://github.com/YT-Advanced/YT-Advanced/assets/87489540/589cb244-5b94-4650-b5f1-bb09cbc596d9)

**Comment by YT-Advanced** [comment]
Cannot see it, A/B Testing ?

**Comment by YT-Advanced** [comment]
if you can, pls inbox my telegram so you can help me export this tab compoment

**Comment by MondayNitro** [comment]
> if you can, pls inbox my telegram so you can help me export this tab compoment

can you please check this channel https://www.youtube.com/@thedeshbhakt
it shows store tab. ive only seen a handful of channels with the store tab

**Comment by YT-Advanced** [comment]
> > if you can, pls inbox my telegram so you can help me export this tab compoment
> 
> can you please check this channel https://www.youtube.com/@thedeshbhakt it shows store tab. ive only seen a handful of channels with the store tab

I have checked it then I can not see it. That's why I reply to you bro

**Comment by YoghurtAndPizza** [comment]
I can't see this tab either.

**Comment by YoghurtAndPizza** [comment]
I can see this tab in CohhCarnage's channel.

**Comment by YT-Advanced** [comment]
Look like it only appear on subscribed channel. Now I can reproduce it !

**Comment by YoghurtAndPizza** [comment]
It actually appears in non-subscribed channels as well.

**Comment by YT-Advanced** [comment]
All thing I can do is hide the product only (not hide fully the tab). If @inotia00 still alive, please help me 😭

**Comment by YT-Advanced** [comment]
Updated in latest version
