### ISSUE TITLE
Regarding Buffering issue

### ISSUE THREAD

**Issue by Johny2074** [YT-Advanced/YT-Advanced#30]
Today I have faced a weird buffering issue. I use YouTube with latest REX patches. Yesterday things were fine but today I have faced buffering issue in only RVX . Despite going incognito mode and change to my second google account the probles is still present in all cases. But in official Revanced 18.23.35 there is no buffering issue in  my Main account, Second account or even incognito mode
I have uninstalled RVX and micro g then reinstalled them again but with no benefits.
I have also turned off spoof player parameters then turned it on but the issue still presents

**Comment by YT-Advanced** [comment]
It is depend on your account. Turn on **Spoof player parameter TYPE** then your bug will be fixed

**Comment by Johny2074** [comment]
Thanks❤️ you are Great developer.

**Comment by jhon1282** [comment]
It doesn't seem like an account problem, starting today even without being logged in you have to activate both parameters, this has been for a few hours 😡.
It looks like Google is doing everything to counter the use of these patches 🙄

**Comment by lowestprime** [comment]
Can not log in microg services core. It does not appear in Samsung accounts anymore either, but vanced microg works fine. 
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/1e36c120-5ab6-44f4-962c-22042dfcf98c)
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/3648c5c6-a405-4022-98e5-0338f0cdc92b)
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/f8667951-7dc5-43e9-819f-2aeda748610a)
