### ISSUE TITLE
Microg bug 

### ISSUE THREAD

**Issue by Adity1243** [YT-Advanced/YT-Advanced#31]
The account didnt getting sign up in latest micro g patch

**Comment by Adity1243** [comment]
![Uploading Screenshot_2023-08-15-15-42-56-993_app.premium.android.youtube.jpg…]()

**Comment by Adity1243** [comment]
![Screenshot_2023-08-15-15-42-56-993_app premium android youtube](https://github.com/YT-Advanced/YT-Advanced/assets/131557644/331cd00a-f93b-466d-bab5-adac8dac63f7)

**Comment by Adity1243** [comment]
![IMG_20230815_154605](https://github.com/YT-Advanced/YT-Advanced/assets/131557644/39a78c25-b428-4009-957f-e84fa8d4cf50)

**Comment by lowestprime** [comment]
For now, this works fine:
https://www.apkmirror.com/apk/team-vanced/microg-youtube-vanced/microg-youtube-vanced-0-2-24-220220-release/#downloads

**Comment by YoghurtAndPizza** [comment]
I highly recommend mMicroG by inotia00, haven't had a zero issue with it.

https://github.com/inotia00/mMicroG

**Comment by Adity1243** [comment]
I think the latest youtube patch dosent support this mmicrog version

**Comment by Adity1243** [comment]
If anyone facing this issue just pach by revancify the latest microg didnt got updated in revancify.

**Comment by lowestprime** [comment]
Just manually downloaded and switched to mMicrog, and it worked flawlessly. But the autodownloaded one through rvx-builder seems incompatible. 
https://github.com/inotia00/mMicroG/releases/tag/v0.2.27.231613

**Comment by YT-Advanced** [comment]
Okay, I will switch to mMicroG by inotia00

**Comment by YT-Advanced** [comment]
Should I create my own MicroG :D
