### ISSUE TITLE
allow "hide account menu" to hide this section

### ISSUE THREAD

**Issue by federicogith** [YT-Advanced/YT-Advanced#32]
I never click on it nor do anything with it.
Allow hide account menu option to hide the highlighted section:
![229147827-ec3be61e-5c78-4268-8a3e-3b0410cd807c](https://github.com/YT-Advanced/YT-Advanced/assets/130296934/29fa77a6-1daa-4b33-b779-4139d6bb5aab)

**Comment by YT-Advanced** [comment]
Lmao .-. Why user always asking to hide all Youtube

**Comment by federicogith** [comment]
It's not possible to do that?

**Comment by YT-Advanced** [comment]
> It's not possible to do that?

I think possible but it is not necessary to hide
