### ISSUE TITLE
bug(hide-music-ads): not working on v5.34.52

### ISSUE THREAD

**Issue by harutoku** [YT-Advanced/YT-Advanced#38]
Type
Error while patching

Tools used
Revancify

Application
YouTube Music v5.34.52

Bug description
The "library" is an older version, version 5.34.52, which does not remove ads.

Steps to reproduce
Step1 In revancify, select "recommended" and apply the patch.
Step 2 Play any of the songs.

**Comment by YT-Advanced** [comment]
Since I didn't worked with YT Music, so I'm not sure that I can implemented it

**Comment by harutoku** [comment]
If you can, that's fine.

**Comment by YT-Advanced** [comment]
@harutoku Can u give me a screenshot of the bug you are facing

**Comment by harutoku** [comment]
![Screenshot_20230824-135532398_1.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/123850345/e25bb482-5767-4797-9278-236c04c4f7ed)

![Screenshot_20230824-135532398.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/123850345/27285eae-6739-4a76-8445-624f19f8ed9b)

![Screenshot_20230824-135709812.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/123850345/5ff3ef32-77f4-4dc6-a735-fd2044cfbc64)

Sorry for the delay in noticing.
In addition, the premium mark shown at the bottom is not gone.
The applied patch is shown on the third page.
This is a Japanese ad.

**Comment by YT-Advanced** [comment]
For the upgrade button, you should use inotia00 ones because you don't have Sample Button

**Comment by harutoku** [comment]
Sorry,What is a sample button?

**Comment by YT-Advanced** [comment]
@harutoku This
![image](https://github.com/YT-Advanced/YT-Advanced/assets/70064328/439f830b-42e4-4bb4-99c2-a19993457ecf)

**Comment by harutoku** [comment]
Originally, when I applied the inotia00 patch to this version of the apk, the sample button and upgrade button were not displayed. (They were displayed in apk version 6.~.) Removing ads was also possible in the old patch version, but since when it is not possible anymore. Please, please implement the function of removing ads.
Or, in the latest version, please make it possible to display the Library button of the old specification.
