### ISSUE TITLE
Video quality getting restricted to 480p after enabling 2160p resolution

### ISSUE THREAD

**Issue by pauliestephen** [YT-Advanced/YT-Advanced#39]
My default video setting is 1080p, and the video performs flawlessly at this resolution. However, when I attempt to select the 2160p option, it reverts back to 480p, and subsequently, I am unable to view any resolutions beyond 480p. I have never faced this issue earlier. This has happened with youtube version 18.31.40 and latest rex patches 2.188.0

![Screenshot_20230816-204233_ReVanced Extended](https://github.com/YT-Advanced/YT-Advanced/assets/133159752/7e44d8fd-af30-453f-9203-bb7a2daacc20)

**Comment by Adity1243** [comment]
That bcus your device max video quality is 1080p can handle.

**Comment by pauliestephen** [comment]
> That bcus your device max video quality is 1080p can handle.or try 1440p quality.

I don't think that will be the case. Earlier I have played 2160p resolution with inotias version

**Comment by YT-Advanced** [comment]
@pauliestephen Can u share the video you are playing ?

**Comment by pauliestephen** [comment]
> @pauliestephen Can u share the video you are playing ?

https://youtu.be/s2xrarUWVRQ

**Comment by YT-Advanced** [comment]
> > @pauliestephen Can u share the video you are playing ?
> 
> https://youtu.be/s2xrarUWVRQ

@pauliestephen Can u test the testpatch

**Comment by pauliestephen** [comment]
> > > @pauliestephen Can u share the video you are playing ?
> > 
> > 
> > https://youtu.be/s2xrarUWVRQ
> 
> @pauliestephen Can u test the testpatch

Where can find the testpatch . I am not seeing that in the available patches.

**Comment by YT-Advanced** [comment]
> Where can find the testpatch . I am not seeing that in the available patches.

You can test this prebuilt ones, then if it worked I will merge into my main repos
https://github.com/YT-Advanced/Debug

**Comment by pauliestephen** [comment]
> > Where can find the testpatch . I am not seeing that in the available patches.
> 
> You can test this prebuilt ones, then if it worked I will merge into my main repos https://github.com/YT-Advanced/Debug

I am not sure.  Can you help me to test it. Is this correct for applying this test patch.
![Screenshot_20230817-152824](https://github.com/YT-Advanced/YT-Advanced/assets/133159752/3372ab02-8a8a-4f41-82db-9ad93ad03697)

**Comment by YT-Advanced** [comment]
@pauliestephen Replace ReX-integrations with testinte

**Comment by pauliestephen** [comment]
@YT-Advanced its working now. Thank you 🙂. I have tested it after applying the test patches.
Proof
![Screenshot_20230817-160834_ReVanced Extended](https://github.com/YT-Advanced/YT-Advanced/assets/133159752/d04be88f-dbb7-4298-a295-32648c327bda)

Can I know what was missing previously for this and what you applied to fix it.

**Comment by pauliestephen** [comment]
@YT-Advanced this one I observed just now. I turned off the phone by pausing the video. And when i opened again , this issue came again.
![Screenshot_20230817-162402_ReVanced Extended](https://github.com/YT-Advanced/YT-Advanced/assets/133159752/ca5a6fcd-0719-427c-a731-f039353291af)

**Comment by 1node00** [comment]
Are you sure you don't have data restriction enabled in your phone network settings?

Also try to switch spoof app version to 18.20.39.

And go to YouTube's settings (not rvx) and set your quality to high on both wifi and cellular.

**Comment by YT-Advanced** [comment]
> Can I know what was missing previously for this and what you applied to fix it.

I do some magic 🤡

**Comment by pauliestephen** [comment]
> Are you sure you don't have data restriction enabled in your phone network settings?
> 
> Also try to switch spoof app version to 18.20.39.
> 
> And go to YouTube's settings (not rvx) and set your quality to high on both wifi and cellular.

No network restrictions enabled and youtube quality set to high on both wifi and cellular.  I observed this is happening for videos having 2160p resolution along with 60fps.  Its not happening for normal 4k videos.

**Comment by YT-Advanced** [comment]
> No network restrictions enabled and youtube quality set to high on both wifi and cellular. I observed this is happening for videos having 2160p resolution along with 60fps. Its not happening for normal 4k videos.

Hmm, seem like I have no idea to solve it. But at least, the bug doesn't happen on normal video, right ?

**Comment by pauliestephen** [comment]
@YT-Advanced its not happening normally. It will happen if you play video and set the resolution to 2160p 60fps resolution. 
are you not facing this in your phone. Can you try once in your phone.

**Comment by Adity1243** [comment]
Try 2160p normal videos 30fps

**Comment by YT-Advanced** [comment]
> @YT-Advanced its not happening normally. It will happen if you play video and set the resolution to 2160p 60fps resolution. are you not facing this in your phone. Can you try once in your phone.

I tried and I'm not facing it. Can some other user try to reproduce it ?

**Comment by pauliestephen** [comment]
> > @YT-Advanced its not happening normally. It will happen if you play video and set the resolution to 2160p 60fps resolution. are you not facing this in your phone. Can you try once in your phone.
> 
> I tried and I'm not facing it. Can some other user try to reproduce it ?

Can you try this once. Open the video and set resolution to 2160p 60 and play the video for sometime and then check the resolution.
https://youtu.be/5y7a1Eb6QR4

May be it will be a issue for my phone.

**Comment by pauliestephen** [comment]
> Try 2160p SDR videos 30fps

These are working fine..no issues

**Comment by Adity1243** [comment]
Did you tried 2160p 60 before ?

**Comment by YT-Advanced** [comment]
> > > @YT-Advanced its not happening normally. It will happen if you play video and set the resolution to 2160p 60fps resolution. are you not facing this in your phone. Can you try once in your phone.
> > 
> > 
> > I tried and I'm not facing it. Can some other user try to reproduce it ?
> 
> Can you try this once. Open the video and set resolution to 2160p 60 and play the video for sometime and then check the resolution. https://youtu.be/5y7a1Eb6QR4
> 
> May be it will be a issue for my phone.

Still cannot reproduce 🤔

**Comment by 1node00** [comment]
Disable hdr in rvx settings and try again.

**Comment by 1node00** [comment]
Also make sure you don't have data saving enabled in YouTube settings.

**Comment by 1node00** [comment]
Looks like YouTube have had this bug before:

https://github.com/inotia00/ReVanced_Extended/issues/321

**Comment by YT-Advanced** [comment]
> Looks like YouTube have had this bug before:
https://github.com/inotia00/ReVanced_Extended/issues/321
So this also could be a A/B testing.

I have solved it in the recent update, then we have this issues 🫠

**Comment by pauliestephen** [comment]
Data saving is disabled, and turning off HDR hasn't resolved the problem. This issue pertains specifically to playing in 4K at 60fps. Playing in 4K 30fps and up to 1440p 60fps is functioning properly. 
Just now i tested  and video played fine at 4k 60 for some time and then i closed and replayed the video again and faced the same issue. This issue seems ambiguous. As many users are not facing this, you can close this issue. Thanks everyone for all the help.
