### ISSUE TITLE
Wrong version of patches shown

### ISSUE THREAD

**Issue by federicogith** [YT-Advanced/YT-Advanced#4]
I'm on patches v2.187.2, but in Miscellaneous > Patches Information still says that I'm on v2.187.1:
![Screenshot_20230809_120450_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/130296934/e05050b3-3aa8-4c92-9124-d0c986363549)

**Comment by YT-Advanced** [comment]
Oh, sorry, my wrong :))) Will fix it in next release

**Comment by federicogith** [comment]
inotia used to close a report when the fix was actually released, in order to show others that the bug was already been reported.
But it is completely up to you.
