### ISSUE TITLE
suggestion(rvx builder): pin right mMicroG link

### ISSUE THREAD

**Issue by girshcatt** [YT-Advanced/YT-Advanced#41]
In my previous issue i asked to change microg that rvx builder download and u changed it to kazimmt's GmsCore v0.2.28.231657, but we need not GmsCore, we need mMicroG from kazimmt https://github.com/kazimmt/mMicroG/releases/download/v0.2.28.232516/microG.apk

**Comment by YoghurtAndPizza** [comment]
Fixed when merged.

**Comment by YT-Advanced** [comment]
Oh okay, I will update
