### ISSUE TITLE
Bug: YTM 6.15.51 Upgrade button still exist

### ISSUE THREAD

**Issue by cyberboh** [YT-Advanced/YT-Advanced#42]
The default patches applied very well, but upgrade button still exist

`INFO: Hide upgrade button succeeded `

Patches version 2.188.0
Integrations version 0.116. 2

Proof:
![Screenshot_20230818_044435](https://github.com/YT-Advanced/YT-Advanced/assets/99109969/0cd61b6a-2e9a-4158-80da-02b13fabb7d4)

**Comment by YT-Advanced** [comment]
Thanks for your report, I will fix it in next update

**Comment by YT-Advanced** [comment]
Fixed in [v2.188.1](https://github.com/YT-Advanced/ReX-patches/releases/tag/v2.188.1)

**Comment by jojobozo** [comment]
> Fixed in [v2.188.1](https://github.com/YT-Advanced/ReX-patches/releases/tag/v2.188.1)

The patches spoof app and translations are failing when I try to patch it, do you know why?

**Comment by iviickysharma** [comment]
![Screenshot_2023-08-19-15-21-50-065_app rvx android apps youtube music](https://github.com/YT-Advanced/YT-Advanced/assets/141261339/fe0af9e4-4be6-4950-b0f6-ef99399fa81b)
Upgrade button successfully 💪 hidden with latest patches.

**Comment by ANi1XO** [comment]
![Screenshot_20230819-183056_YouTube Music](https://github.com/YT-Advanced/YT-Advanced/assets/113413955/eae885c5-5aff-448c-95c2-2b769fb832c6)
Instead of upgrade button, samples button is being hidden
Yt-music v6.15.51 patches v.2.188.1

**Comment by YT-Advanced** [comment]
@ANi1XO Seem like Sample button don't showed in your side. You should change to another account that have Sample Tab or use inotia00 version

**Comment by ANi1XO** [comment]
> @ANi1XO Seem like Sample button don't showed in your side. You should change to another account that have Sample Tab or use inotia00 version

Yes samples button was showing up in inotia00 version, but then library button was missing. I think i can live without samples button but library button is crucial for me. So I'll stick with this version for the time being. Let's hope it gets completely fixed in the update.

**Comment by cyberboh** [comment]
> @ANi1XO Seem like Sample button don't showed in your side. You should change to another account that have Sample Tab or use inotia00 version

I have same issue, sample button is gone and upgrade button is not hidden.
My account before had sample button (see screenshot from this issue) , but after repatch with new patches, then it's gone.

**Comment by ANi1XO** [comment]
> > @ANi1XO Seem like Sample button don't showed in your side. You should change to another account that have Sample Tab or use inotia00 version
> 
> I have same issue, sample button is gone and upgrade button is not hidden. My account before had sample button (see screenshot from this issue) , but after repatch with new patches, then it's gone.

So my issue got completely fixed after a server side update from YouTube. I suggest you wait 24-48hours. The patch is working as expected for me RN.
