### ISSUE TITLE
Severe Bug: YTM 6.15.51 Many patches failed to be applied

### ISSUE THREAD

**Issue by cyberboh** [YT-Advanced/YT-Advanced#45]
Just updated the patches and Integrations to the latest one, but almost of all failed to be applied
See the log below
[patch_log.txt](https://github.com/YT-Advanced/YT-Advanced/files/12385294/patch_log.txt)

**Comment by YT-Advanced** [comment]
@cyberboh Can u try to patch again ? I have fixed it

**Comment by cyberboh** [comment]
> @cyberboh Can u try to patch again ? I have fixed it

fixed mate, thank you.
