### ISSUE TITLE
Add background chip to Search Bar as well, similar to action buttons and comment box

### ISSUE THREAD

**Issue by AdishSagarawat** [YT-Advanced/YT-Advanced#46]
Because it improves the interface design a bit. 

See below :

Yt Advanced:

![photo_2023-08-19_15-45-10](https://github.com/YT-Advanced/YT-Advanced/assets/69076256/4a43e93f-d62f-4280-abd0-fa5e0f329b72)

YT Stock: (Yeah, that circular chip around Voice Search icons looks nice as well!)

![photo_2023-08-19_15-45-13](https://github.com/YT-Advanced/YT-Advanced/assets/69076256/99248f60-25fd-4e8d-9b1d-b14c04e6d525)

YT Advanced, chip of Action Buttons and Comment Box:

![Screenshot_20230819-155138_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/69076256/621a5c5f-12f8-4516-9209-1f52afb1658d)

**Comment by YT-Advanced** [comment]
You can exclude `theme` patch to get the original chip (also whole Youtube)
