### ISSUE TITLE
bug(SponsorBlock): these three settings can't be imported/exported

### ISSUE THREAD

**Issue by girshcatt** [YT-Advanced/YT-Advanced#47]
This is issue that appears in ReVanced too, this three settings on photo can't be exported/imported, these settings not exist in SponsorBlock JSON config
![Screenshot_20230819_201141_ReVanced Extended](https://github.com/YT-Advanced/YT-Advanced/assets/110785596/e9b271bc-687a-4b25-bb96-851076036f43)

**Comment by YT-Advanced** [comment]
Is it happen on Revanced too ?

**Comment by girshcatt** [comment]
In SponsorBlock settings In revanced i tried to switch all off, export settings, switch all on and import settings. It's much worse in RV, Use compact skip button, Show voting button and Automatically hide skip button not implemented in JSON config

**Comment by YT-Advanced** [comment]
> In SponsorBlock settings In revanced i tried to switch all off, export settings, switch all on and import settings. I

Ah, I see. I will take a look with this issues

**Comment by girshcatt** [comment]
ok, thx

**Comment by YT-Advanced** [comment]
> ok, thx

Can u share me an example json file of SponsorBlock. Now I'm using PC so cannot export it

**Comment by YT-Advanced** [comment]
@girshcatt Any toast show when you import ?

**Comment by girshcatt** [comment]
Settings successfully imported toast

**Comment by girshcatt** [comment]
STOP, i tested this like i tested it in revanced and i so dumb that i didn't do it before, sorry, now we can be sure that this bug 100% similar as in ReVanced, this three settings not implement in json config

**Comment by girshcatt** [comment]
I edited issue, and now issue written correct, Hoàng Gia Bảo please sorry for my dumbness
