### ISSUE TITLE
Request: Whitelist option for Alternative Thumbnails feature

### ISSUE THREAD

**Issue by 1node00** [YT-Advanced/YT-Advanced#50]
There are channels that doesn't have clickbait thumbnails, so it would be awesome if we could get a whitelist feature for it (similar to SponsorBlock).

I know Alternative Thumbnails and upcoming  DeArrow is still in a work in progress state, but in the future this would be handy addition.

**Comment by YT-Advanced** [comment]
I have thought about Whitelist for Alternative Thumbnails. But I cannot find a way to make it
