### ISSUE TITLE
Bug: hide-upgrade-button

### ISSUE THREAD

**Issue by ANi1XO** [YT-Advanced/YT-Advanced#51]
Instead of hiding upgrade button, this patch is hiding samples button
Yt-music v6.15.51, ReX patches v2.188.1.
![Screenshot_20230819-183056_YouTube Music](https://github.com/YT-Advanced/YT-Advanced/assets/113413955/23a30aff-1549-49e5-98d2-d2083499bd9b)

**Comment by YT-Advanced** [comment]
It caused because Sample button is not showed in your side. You can use inotia00 ones
