### ISSUE TITLE
bug(Youtube) quick action doesnt work

### ISSUE THREAD

**Issue by andylee516** [YT-Advanced/YT-Advanced#53]
![Screenshot_20230820_001247_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/113352087/ca8c7c12-dbe1-4941-918b-9e28987aacc1)
![Screenshot_20230820_001319_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/113352087/5e75383c-b84f-4469-ac03-8b6c8ed2784b)

when we watch video in full screen, quick action does not shows despite i turned it on. yt version is 18.31.40 and patch version 2.188.1

**Comment by YT-Advanced** [comment]
Seem like Google removed it from their server side. Can you update your ORIGINAL Youtube to latest version and test ?

**Comment by YT-Advanced** [comment]
@andylee516 Turned off Hide Full Screen Panel then it will be solved
