### ISSUE TITLE
Minimizing videos that contain chapters is laggy

### ISSUE THREAD

**Issue by Mohammed1520** [YT-Advanced/YT-Advanced#54]
There is Known issue in RVX . But not in official YouTube or official Revanced. 
https://github.com/inotia00/ReVanced_Extended/issues/1016
Inotia had said he can't fix it. I inquire if you could solve this issue 🙏

**Comment by YT-Advanced** [comment]
This bug solved ?

**Comment by Mohammed1520** [comment]
Yes I didn't notice it in YouTube 18.33.xx anymore
