### ISSUE TITLE
Irrelevant & useless text in Video Quality Selector Menu.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [YT-Advanced/YT-Advanced#58]
This text provides useless & irrelevant information, so please add an option to hide it.

![IMG_20230820_143831.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/91815107/52ad73f9-f479-45bf-b41d-5585191c3f72)

**Comment by Wojtaz0w** [comment]
It is also misleading, because rvx provides support for saving video quality and for default quality. This text may cause some users to feel confused.

**Comment by TabS9Ultra** [comment]
The patch is nor working on my end.

**Comment by Mohammed1520** [comment]
It is not working in my device

**Comment by kazimmt** [comment]
> The patch is not working on my end.

Enable the setting & restart the app
![IMG_20230901_143214](https://github.com/YT-Advanced/YT-Advanced/assets/82371061/116a5c1c-94d2-4f63-9419-096b13dd71b8)

@Mohammed1520

**Comment by TabS9Ultra** [comment]
Not working.

![Screenshot_20230901_120819_ReVanced Extended](https://github.com/YT-Advanced/YT-Advanced/assets/143272767/85f95979-c5ae-4e2c-baee-3d4aaec71ee2)

**Comment by MrNorthernLights** [comment]
I also noticed that when I opened revanced manager again and selected patches, this patch was gone. It was there when I patched earlier but now its gone.

**Comment by MrNorthernLights** [comment]
Also, about patches window is showing only 92 patches in total, even though I added in 98 patches. And this patch is not on the list, even though I have it and its enabled.

**Comment by MrNorthernLights** [comment]
I uninstalled revanced manager and reinstalled, repatched. Uninstalled youtube and reinstalled, still not working.

@kazimmt
