### ISSUE TITLE
Video Quality Preset not worked in RVX

### ISSUE THREAD

**Issue by Mohammedibrahim15** [YT-Advanced/YT-Advanced#6]
Hi ,may be it is not the right place for issues but i can't find issue section in REX repository 
I have read that you will continue developing RVX . I wonder if you could solve that issue 
https://github.com/inotia00/ReVanced_Extended/issues/321
It works fine with official Revanced but in RVX it doesn't work as intended 
And please can you create any mean for communication about REX patches and issues such as telegram channel for example
Thank you in advance

**Comment by YT-Advanced** [comment]
First, I will try to use the code from Revanced to fix it
Second, I am not planning to create a community because I'm not sure about continue

**Comment by Mohammedibrahim15** [comment]
Thanks for your response
If your time permits, you could release monthly update including YouTube version update and some fixes if this wouldn't annoy you 
By this way you can avoid burn out of deveping RVX 
This is just a suggestion and thanks for your great efforts ❤️

**Comment by Mohammed1520** [comment]
I have the Same issue. Let's waite for upcoming updates,so it will be solved

**Comment by Adity1243** [comment]
> Hi ,may be it is not the right place for issues but i can't find issue section in REX repository I have read that you will continue developing RVX . I wonder if you could solve that issue [inotia00/ReVanced_Extended#321](https://github.com/inotia00/ReVanced_Extended/issues/321) It works fine with official Revanced but in RVX it doesn't work as intended And please can you create any mean for communication about REX patches and issues such as telegram channel for example Thank you in advance

This is same issue occured while inotia00 working with revanced extended can you try to disable force vp9 codec option and play video again ?

**Comment by Adity1243** [comment]
If your device already supports to vp9 codec there is no need to enable that option it will break the video quality preset settings.

**Comment by Adity1243** [comment]
This issue is not reproducing in my device

**Comment by Mohammed1520** [comment]
![Screenshot_20230813_135446_app rvx android youtube_edit_2211504081952](https://github.com/YT-Advanced/YT-Advanced/assets/107951133/f0bce1ba-0449-4745-98bf-23fdb17f4898)
![Screenshot_20230813_135457_app rvx android youtube_edit_2202364103829](https://github.com/YT-Advanced/YT-Advanced/assets/107951133/fde8f2d8-f1a7-4951-b9b8-8d8a0564aa4c)
In my device 
HDR video is enabled and force v9 is disabled.. when this issue occured I thought it is related to my Google account but when I used Official Revanced it disappeared
So it seems that is not related to my account

**Comment by Adity1243** [comment]
Your wifi settings is set to 360p bro

**Comment by Adity1243** [comment]
And why only 2 options available there in vp9 section

**Comment by Adity1243** [comment]
Bro did you patched correctly where are other options or you downloaded by website.

**Comment by Mohammed1520** [comment]
No it is one option.. the upper part of this photo is another option 
![Screenshot_20230813_141024_app rvx android youtube](https://github.com/YT-Advanced/YT-Advanced/assets/107951133/f65e8680-160c-4b7d-99ff-c446f6dd47d3)
And regarding WIFI  video quality. Unfortunately the internet in ky county is limited so I have to watch videos in that quality to preserve my internet quota 😅😅

**Comment by YT-Advanced** [comment]
Dear all, the code from Revanced and RVX is the same, that is why inotia00 cannot solved this problem too :))) Hope an intelligent person saw this issues and leave a pull request

**Comment by Adity1243** [comment]
Try enable cronet engine quick protocol

**Comment by Adity1243** [comment]
> No it is one option.. the upper part of this photo is another option .Here is full screenshot ![Screenshot_20230813_141024_app rvx android youtube](https://user-images.githubusercontent.com/107951133/260298728-f65e8680-160c-4b7d-99ff-c446f6dd47d3.jpg) And regarding WIFI video quality. Unfortunately the internet in ky county is limited so I have to watch videos in that quality to preserve my internet quota 😅😅
 
@

**Comment by Mohammed1520** [comment]
Nothing happens.. the issue still presents

> Try enable cronet engine quick protocol

**Comment by Adity1243** [comment]
@Mohammed1520 Aah, i dont know what is happening with your youtube this issue is not reproducing in my device as you mention your country limits the wifi usage maybe that causing the issue you can try using other country vpn like USA,etc. Last option.

**Comment by Mohammed1520** [comment]
I tried but also no effect
Things are fine in official Revanced
And were fine in RVX. In May inotia had reflected some commits in default video quality, then the problem occured 
After that inotia had removed these commits so everything worked fine from that time to First days of July. 
The problem reappears after first patch released by inotia after returning from vacation (https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)

Refer to that issue (https://github.com/inotia00/ReVanced_Extended/issues/1006#event-9238961936)
 .

**Comment by YT-Advanced** [comment]
> I tried but also no effect
> Things are fine in official Revanced
> And were fine in RVX. In May inotia had reflected some commits in default video quality, then the problem occured 
> After that inotia had removed these commits so everything worked fine from that time to First days of July. 
> The problem reappears after first patch released by inotia after returning from vacation (https://github.com/inotia00/revanced-patches/releases/tag/v2.181.1)
> 
> Refer to that issue (https://github.com/inotia00/ReVanced_Extended/issues/1006#event-9238961936)
>  .

Maybe I will try to revert inotia00 changes

**Comment by YT-Advanced** [comment]
@Mohammed1520 Are u active, I have released a fix via Testpatch and Testinte. Can you test it ?

**Comment by YT-Advanced** [comment]
Updated on latest patch version. Please let me know if it worked

**Comment by Mohammed1520** [comment]
Thank you you are amazing
Now it works fine ❤️
