### ISSUE TITLE
Request: Better PiP

### ISSUE THREAD

**Issue by sliceanddice9** [YT-Advanced/YT-Advanced#60]
There are no back & forward seek media buttons on the PiP floating window when playing videos minimized. If there were seek buttons on the Picture-In-Picture mode than we wouldn't have to maximize to the foreground the app itself in order to access the touch input, double tap, video player controls for going back or forward by 10 seconds.

Having the back & forward seek media buttons for the background play funtion on the lockscreen would also be great as well.

NewPipe's version of PiP & background play for lockscreen includes these seek media controls

![221494304-391cbe60-086b-4d9d-aef9-bb5fc95c6da5](https://github.com/YT-Advanced/YT-Advanced/assets/59092472/1ce328c2-b058-47c2-acdb-a74fc4b8c47b)

**Comment by Hennadz** [comment]
Do not distract the dude with all kinds of nonsense..
These buttons are available in the notification.

**Comment by sliceanddice9** [comment]
> Do not distract the dude with all kinds of nonsense.. These buttons are available in the notification.

What or where is the "notification"? If you mean the "Lock screen and media controls" setting from "Manage Notifications" under "App info" than no - there is no way at all to gain these seek back and forward buttons for PiP or lockscreen background play.

**Comment by sliceanddice9** [comment]
> Do not distract the dude with all kinds of nonsense.. These buttons are available in the notification.

No, there are no back and forward seek media buttons in the notification while the Picture-In-Picture mode is active. You can adjust the seekbar slider in the notification but as I said there are no actual back and forward seek media buttons to be found. Besides my request is for the back and forward seek media buttons to actually appear on the PiP floating window itself.

**Comment by Hennadz** [comment]
> No you are wrong

What are you missing here?

![Screenshot_20230824-145822_One UI Home](https://github.com/YT-Advanced/YT-Advanced/assets/130844239/17e06c54-c717-4c26-ab64-7007d7c6183c)

**Comment by sliceanddice9** [comment]
> > No you are wrong
> 
> What are you missing here?
> 
> ![Screenshot_20230824-145822_One UI Home](https://user-images.githubusercontent.com/130844239/262966126-17e06c54-c717-4c26-ab64-7007d7c6183c.png)

How much clearer do I need to be? I'm talking about seek media buttons that when tapped can go backwards by 5 or 10 seconds or forwards by 5 or 10 seconds. Those buttons in the notification are NOT seek media buttons. Those buttons in the notification are for skipping between videos from one video to another video.
