### ISSUE TITLE
Quick Actions off-tab settings

### ISSUE THREAD

**Issue by Alxon4789** [YT-Advanced/YT-Advanced#66]
Hi,
I wanted to patch YouTube with your patches for the first time today using Revancify. The patching process itself went through smoothly, but when wanting to configure the already patched app, I noticed that one section of the settings was out of "tab". I don't know what the reason could be, all the information (which I think you will need, attached below). If you would like to explain/help, I would be very grateful

YouTube 18.32.39
Patches v2.188.2
The tool I patched with: Revancify with root
[patch_log.txt](https://github.com/YT-Advanced/YT-Advanced/files/12420852/patch_log.txt)

![photo_2023-08-23_15-44-22](https://github.com/YT-Advanced/YT-Advanced/assets/143010511/a3263eaa-a0ad-4c65-a990-b06247545027)

**Comment by YT-Advanced** [comment]
You are turning on Hide Quick Action Container, so all Hide below will be turned off
