### ISSUE TITLE
Patch:Force Av01 codec

### ISSUE THREAD

**Issue by Adity1243** [YT-Advanced/YT-Advanced#69]
Can you add force av01 codec in youtube just like vp9 codec .

**Comment by YT-Advanced** [comment]
Huh, by default Youtube always use av01

**Comment by Adity1243** [comment]
No its using vp9 codec

**Comment by YT-Advanced** [comment]
> No its using vp9 codec

If it used vp9, that mean the video is too old and don't have av01 codec ones to use

**Comment by Adity1243** [comment]
It uses every time

**Comment by YT-Advanced** [comment]
> It uses every time

I think it because your device are not supported it
