### ISSUE TITLE
Audio Playback Patch Failed : YT Music

### ISSUE THREAD

**Issue by selfmusing** [YT-Advanced/YT-Advanced#70]
I've tried to patch YT Music v6.16.52 , but audio playback patch failed , meanwhile all other patches worked fine .
[YTM-6.16.52-patch_log.txt](https://github.com/YT-Advanced/YT-Advanced/files/12426431/YTM-6.16.52-patch_log.txt)
( here is the patch log file )

**Comment by YT-Advanced** [comment]
Thanks
