### ISSUE TITLE
Enhanced Like and Dislike Button Visibility 

### ISSUE THREAD

**Issue by ImpenetrableNoble** [YT-Advanced/YT-Advanced#72]
**Problem One:**
I've encountered problems with the like button in version 18.32.39. I've noticed unusual letters, symbols, and commas appearing in the YouTube like button. This issue requires prompt attention and should be resolved without delay.

**Problem Two:**
 Users often find it difficult to quickly and accurately perceive the actual number of likes and dislikes on YouTube videos, as the current design of the like and dislike buttons doesn't prioritize visibility. This lack of clarity can lead to misunderstandings about the community's sentiment towards a video and can hinder meaningful engagement. 

**Solution:** 

Implement a more visually prominent display of like and dislike counts that enhances user experience and provides clearer insights into the community's response to videos. 

**Implementation:** 

1. **Increase Font Size and Boldness:** Enlarge the font size of the like and dislike numbers and make them slightly bolder to draw immediate attention. This will help users quickly identify the number of likes and dislikes without straining their eyes.
 
2. **Distinct Color Coding:** Maintain the existing color scheme for like (green) and dislike (red) buttons, but also apply the same color to the corresponding like and dislike count numbers. This consistency will create a clear association between the button and its corresponding count.
 
3. **Positioning:** Position the like and dislike counts right next to or beneath their respective buttons. Placing the numbers in close proximity to the buttons will create a natural visual connection and help users easily match the counts with the buttons. 

4. **Hover Effect:** Incorporate a subtle hover effect that enlarges the like and dislike count numbers slightly when a user hovers their cursor over the buttons. This dynamic effect will provide an interactive element and make it even easier for users to spot the counts. 

5. **Simplified Count Formatting:** Present the counts in a user-friendly format that is easy to comprehend, even for videos with a large number of likes and dislikes. For instance, instead of displaying "1,234,567 likes," show "1.2M likes." 

6. **Mobile-Friendly Design:** Ensure that the enhanced visibility features translate well to mobile devices by optimizing font sizes and spacing for smaller screens. 

**Benefits:**

 1. **Improved User Engagement:** By making the like and dislike counts more visible and understandable, users will be more informed about the video's reception and can engage in more meaningful discussions. 
 
2. **Reduced Misinterpretation:** Clearer visibility of the like and dislike numbers will reduce the chance of users misinterpreting the community's sentiment, leading to a more accurate representation of the video's popularity. 

3. **Enhanced User Satisfaction:** Users will appreciate the effort to improve the user interface, making their interactions with the platform more enjoyable and informative.

4. **Increased Transparency:** Transparent communication through visible like and dislike counts will foster trust between content creators and viewers. 

5. **Consistent Design Language:** The proposed enhancements maintain consistency with YouTube's existing design language, ensuring familiarity while offering improved usability. Implementing these suggestions will not only enhance the user experience on YouTube but also contribute to a more informed and engaged community by providing a clearer view of the likes and dislikes on videos.

**Comment by YT-Advanced** [comment]
For problem one, any screenshot ?

**Comment by PenetrableVagina** [comment]
For the issue 1, why dont you just add a screenshot?

**Comment by ImpenetrableNoble** [comment]
![262806190-698bc566-45df-41c9-a8bf-a7d31dcb2d1d](https://github.com/YT-Advanced/YT-Advanced/assets/104534608/477e9a37-6a06-4e7e-9f05-601592039a61)

Thank for you the suggestion of adding a screenshot, my apologies.

**Comment by YT-Advanced** [comment]
> ![262806190-698bc566-45df-41c9-a8bf-a7d31dcb2d1d](https://github.com/YT-Advanced/YT-Advanced/assets/104534608/477e9a37-6a06-4e7e-9f05-601592039a61)
> 
> Thank for you the suggestion of adding a screenshot, my apologies.

It is not bug lol. You can go to RYD Setting and enable Conpact Like Button
