### ISSUE TITLE
Hide upgrade button patch : YT Music

### ISSUE THREAD

**Issue by selfmusing** [YT-Advanced/YT-Advanced#74]
I've patched YTM v6.16.52 via latest Re𝕏 Patches
So I noticed now the Hide upgrade button patch is just hiding the last button , doesn't matter if someone have Samples button in the navigation bar or not.

But it creates an issue if someone has premium subscription :

If someone have premium subscription then the hide upgrade button is already hidden by default for them.
But if we select this patch - then it hide Library button from the navigation bar :)

![Screenshot_20230826-001232_YouTube_Music](https://github.com/YT-Advanced/YT-Advanced/assets/109387456/ac032c1d-09c2-40de-bc35-c2000bc96620)

If I don't select the hide upgrade button then it works normally ( coz the upgrade button already hidden due to premium benefits ) :

![Screenshot_20230826-002628_YouTube_Music](https://github.com/YT-Advanced/YT-Advanced/assets/109387456/e23baa34-d31e-44ef-8220-9f2771aeddbe)

**Comment by kazimmt** [comment]
Why do you want to Select Hide upgrade button if you've a premium subscription?
It makes no sense.
