### ISSUE TITLE
Import settings doesn't work properly 

### ISSUE THREAD

**Issue by Mohammed1520** [YT-Advanced/YT-Advanced#78]
Hi Sir
I have this issue. Import settings doesn't work at the first time, so I Have to click " import settings" once more time to apply 
This video illustrates the issue

https://github.com/YT-Advanced/YT-Advanced/assets/107951133/804adb61-34bf-4d66-93c7-71a3604f6af8

**Comment by TabS9Ultra** [comment]
Unable to repro, works after 1st attempt on my end.

**Comment by Adity1243** [comment]
This happen first time on my device when i tried inotia00 patch but it applies the seeting but dosent show that it got applied.

**Comment by Mohammed1520** [comment]
Oh 
It is already applied but doesn't show toast message so it is seem not to be error 
Thank you 
I will close the issue
