### ISSUE TITLE
hide Stable volume menu

### ISSUE THREAD

**Issue by Kuddus73** [YT-Advanced/YT-Advanced#8]
![Screenshot_20230809_132819_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/127908708/4ee721aa-9efc-463e-a3e6-04a7ec1ab844)

**Comment by YT-Advanced** [comment]
Look like it is A/B testing. Cannot get it in my device

**Comment by Kuddus73** [comment]
Oh, I saw someone else reporting this few days ago and I just got it this morning, so I think you will be able to see it too in the upcoming days
