### ISSUE TITLE
request: playbacks in following feed

### ISSUE THREAD

**Issue by mexon86** [YT-Advanced/YT-Advanced#80]
there is option called playbacks in feed and it allow to video to start play automaticly while we r on the home page or in following page but the problem is when this videos start it saved in watch history and youtube show recomended videos based on watch history so if there will be option to enable this auto playbacks of videos to only play in following tab and not on home page that will be great and i can start to use this feature

**Comment by panam510** [comment]
I have the same request as he does.

To add, only when "Spoof player parameter" is enabled and the spoof type is "Incognito," the videos that are automatically played on the feed are also added to the playback history.

If "Spoof player parameter" is disabled, or if enabled but the spoof type is "Shorts," the video will not be added to the history. This behavior appears to be the same as the official YouTube app, which I would prefer.
