### ISSUE TITLE
[Request] Could Sponsorblock work when casting to TV?

### ISSUE THREAD

**Issue by bloopiy** [YT-Advanced/YT-Advanced#81]
Could sponsorblock skippping work when casting to TV or else where. Works with UYou+ on iOS (meaning segments to be skipped get skipped by the iPhone and so gets skipped on TV, but with ReX the video plays normally through the segments) so I'm guessing the current sponsorblock implementation could be modified for it to work with TV too.

**Comment by YT-Advanced** [comment]
Nah no way lol
