### ISSUE TITLE
Can't patch using RVX manager

### ISSUE THREAD

**Issue by DiofyZz** [YT-Advanced/YT-Advanced#84]
Trying to apply ReX patches using RVX manager but it always gets stuck at "Creating working directory" step both for YouTube and YT Music. 
Cleared app data and reinstalled. Also deleted all revanced YT/music related .sh files in /data/adb/... and /data/local/... folders. What should i do with that? 
![Screenshot_20230827-215713](https://github.com/YT-Advanced/YT-Advanced/assets/136701919/c7fbce35-5811-4f90-8621-6f9dee8b3bf6)

**Comment by speedlorenzo12** [comment]
in my opinion it would be better to fork Revanced Manager and rename it ReX Manager and change the apk name

**Comment by YT-Advanced** [comment]
Recently I have changed my patch to compatiable with Revanced Manager, so you should use it instead

**Comment by TabS9Ultra** [comment]
Tried revanced manager, I'm getting java error and patching gets aborted. So there is some compatibility issues.
