### ISSUE TITLE
ReX : unable to load patches on Revanced Manager

### ISSUE THREAD

**Issue by naokoshoto** [YT-Advanced/YT-Advanced#86]
##  Test case
I installed Revanced Manager with version 1.9.4 and set the Resource Sources as below
![image](https://github.com/YT-Advanced/YT-Advanced/assets/25972975/de7eee41-63fd-4765-8461-0832fdbde984) ![image](https://github.com/YT-Advanced/YT-Advanced/assets/25972975/e9a30422-8040-430a-abbc-a49b9f6821f8)
Then restart the app and patch Youtube with it

##  Expected Result
- Patch are loaded
- App list are appeared

## Issues
- No patches loaded, even version refuse to load
- App List doesn't appeared

![image](https://github.com/YT-Advanced/YT-Advanced/assets/25972975/d9ea4aaa-5076-41b7-a1cb-161a2dcdc361)
![image](https://github.com/YT-Advanced/YT-Advanced/assets/25972975/00ec2879-903d-4384-83cc-73ce91c7d164)

**Comment by YT-Advanced** [comment]
@naokoshoto Can you change the `api.revanced.app` to `api.github.com` and try again ?

**Comment by naokoshoto** [comment]
> @naokoshoto Can you change the `api.revanced.app` to `api.github.com` and try again ?

- Version of patches loaded
- App list doesn't load still
- Unable to fetch Manager updates

**Comment by YT-Advanced** [comment]
I have reverted back !

**Comment by kulmegil** [comment]
How is this resolved? 
I still have empty apps list.
Cannot install as root at all since it's reserved for installed apps only.
