### ISSUE TITLE
Videos not showing up in the Subscriptions tab

### ISSUE THREAD

**Issue by Unicron0** [YT-Advanced/YT-Advanced#89]
![Screenshot_20230828_173220_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/112748462/de32e056-e5d8-4fb0-a6ae-1304eb97fa53)
![Screenshot_20230828_173601_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/112748462/df7d7f74-f7b3-405e-91ab-99d1bdf2b668)
hello. I'm using a Galaxy Tab S7+ to watch YouTube Revanced Extended. I didn't have this issue with 18.25.40, but with every version since, it happens. I've uninstalled and reinstalled ReVanced Extended, including microg, but the issue is the same.
However, for apps created with rvx bulider, the UI also displays correctly.

**Comment by YT-Advanced** [comment]
Can u turn off all setting then turn on one by one to check ?

**Comment by Unicron0** [comment]
> Can u turn off all setting then turn on one by one to check ?

There are so many options, it seems like it would take forever.
RVX apps after 18.25.40 only show 4 videos on the home screen when installing, instead of 6 videos on the screen, so I wonder if there are different UI options.

**Comment by YT-Advanced** [comment]
no, you should spilit setting to seperate option for checking instead of turn off and on one by one
