### ISSUE TITLE
Bug: Custom Filters is broken (worked perfectly in 18.27.36)

### ISSUE THREAD

**Issue by YoghurtAndPizza** [YT-Advanced/YT-Advanced#9]
Now that inotia00 is gone, and therefore no longer fixing bugs. Can you look into this bug, it started like 3 patches ago. It used to work perfectly in 18.27.36 but patches after that broke it completely.

I tried to patch with Revanced Manager (inotia00), Revancify and Revancify X but Custom Filters is still broken. Seems like after making changes, applying and restarting the changes I made are not taking any effect.

It's broken in 18.30.37, patch 2.187.1.

**Comment by YT-Advanced** [comment]
> Now that inotia00 is gone, and therefore no longer fixing bugs. Can you look into this bug, it started like 3 patches ago. It used to work perfectly in 18.27.36 but patches after that broke it completely.
> 
> I tried to patch with Revanced Manager (inotia00), Revancify and Revancify X but Custom Filters is still broken. Seems like after making changes, applying and restarting the changes I made are not taking any effect.
> 
> It's broken in 18.30.37, patch 2.187.1.

I think it is your device issues. I used it to test and create my new patch yesterday

**Comment by YoghurtAndPizza** [comment]
I don't get it, I uninstalled and reinstalled multiple times yet Custom Filters is still broken. :(

**Comment by YT-Advanced** [comment]
> I don't get it, I uninstalled and reinstalled multiple times yet Custom Filters is still broken. :(

Hmm, strange. Can you share the compoment you want to hide, so I can create a patch for it ?

**Comment by YoghurtAndPizza** [comment]
I tried to hide these:

related_video
subscribe_button

**Comment by YT-Advanced** [comment]
> I tried to hide these:
> 
> related_video subscribe_button

Wait. subscribe_button. I thought it have an option to hide ?

**Comment by YoghurtAndPizza** [comment]
No, it doesn't have that option yet, aa far as I know.

**Comment by YT-Advanced** [comment]
> No, it doesn't have that option yet, as far as I know.

Okay, I will implement it. But I will not add `related_video`

**Comment by YoghurtAndPizza** [comment]
Why not add that in too? It's really useful to reduce clutter and keep focus on the video you're watching.

**Comment by YT-Advanced** [comment]
> Why not add that in too? It's really useful to reduce clutter and keep focus on the video you're watching.

Not many user want to hide it :(

**Comment by YoghurtAndPizza** [comment]
Those users can still turn this option off if they don't like it. I'm certain that there are users who would appreciate this. Especially students who want to only focus on the video they are watching.

**Comment by YT-Advanced** [comment]
> Those users can still turn this option off if they don't like it. I'm certain that there are users who would appreciate this. Especially students who want to only focus on the video they are watching.

I know, but some user may inbox me and ask: "Hey bro, why the recommended video is not shown". But I may add it if I have suggested from more users.

**Comment by BrilliantlyEducated** [comment]
> > No, it doesn't have that option yet, as far as I know.
> 
> Okay, I will implement it. But I will not add `related_video`

you don't have to implement it, they can type compact_subscribe_button in the custom filters to hide the Subscribe button

**Comment by YoghurtAndPizza** [comment]
Still not working, I've tried all the possible names and nothing is working.

**Comment by BrilliantlyEducated** [comment]
> Still not working, I've tried all the possible names and nothing is working. I don't understand what could've break this feature, it worked perfectly in 18.27.36. Changes are not taking any effect.

it's working for me, i don't why it's not working for you

**Comment by BrilliantlyEducated** [comment]
> Still not working, I've tried all the possible names and nothing is working. I don't understand what could've break this feature, it worked perfectly in 18.27.36. Changes are not taking any effect.

send a screenshot of your custom filters

**Comment by YoghurtAndPizza** [comment]
I mentioned them here:

https://github.com/YT-Advanced/YT-Advanced/issues/9#issuecomment-1673034054

**Comment by BrilliantlyEducated** [comment]
> I mentioned them here:
> 
> https://github.com/YT-Advanced/YT-Advanced/issues/9#issuecomment-1673034054
> 
> I've used these same exact filters ever since Custom Filters was implemented, but now all of a sudden they stopped working completely. Tried different patching methods, tried different YouTube app versions, tried different spoof versions but no luck. I don't know what happened after 18.27.36 version, but something was added in that broke Custom Filters for me.
> 
> Custom Filters being broken is the only issue I'm having, everything else is working smoothly. I wish @inotia00 was still here, he could have some ideas what is causing this issue.

let me see how you typed it, please send a screenshot

**Comment by YoghurtAndPizza** [comment]
![Screenshot_20230811_124204_ReVanced Extended](https://github.com/YT-Advanced/YT-Advanced/assets/141920927/9505b55b-4e6d-4803-bb26-5f9eafae2170)

**Comment by BrilliantlyEducated** [comment]
> ![Screenshot_20230811_124204_ReVanced Extended](https://github.com/YT-Advanced/YT-Advanced/assets/141920927/9505b55b-4e6d-4803-bb26-5f9eafae2170)
> 

the way you typed it is wrong, clear it all and copy and paste this on custom filters:

 compact_subscribe_button,related_video

and then restart the app

**Comment by YoghurtAndPizza** [comment]
It worked! But I don't understand one thing, why my way was not working? It used to work in the past, was it changed?

I remember it used to be like this:

test_button,test_button

Then it got changed like this:

test_button
test_button

So it got changed back to original form at some point without me noticing it?

**Comment by YoghurtAndPizza** [comment]
Also the description here is wrong.

![Screenshot_20230811_130008_ReVanced Extended](https://github.com/YT-Advanced/YT-Advanced/assets/141920927/746cedcd-14a8-4eb7-ada0-5883d67d9610)

**Comment by YT-Advanced** [comment]
Okay, I will fix it lol

**Comment by YoghurtAndPizza** [comment]
It should be like this:

Filter component names by comma
