### ISSUE TITLE
About CLI rib lib feature 

### ISSUE THREAD

**Issue by Mohammedibrahim15** [YT-Advanced/YT-Advanced#90]
Revanced has recently updated cli so it may work with REX without crash 
But i inquire if you sir can add a rip lib feature that was added by inotia in his fork?
Thank you

**Comment by STEK1337** [comment]
Use [revanced-cli by j-hc](https://github.com/j-hc/revanced-cli/releases/tag/v3.0.1)

**Comment by YT-Advanced** [comment]
I have added it to rvx-builder !

**Comment by Mohammedibrahim15** [comment]
Can you add it to revancify too

**Comment by STEK1337** [comment]
> I have added it to rvx-builder !

Better cli fork [https://github.com/rahulkhatri137/revanced-cli]

**Comment by Mohammed1520** [comment]
It would be great if added also to revancify
