### ISSUE TITLE
Can't patch using revanced manager 1.9.4

### ISSUE THREAD

**Issue by Turhvjbufv** [YT-Advanced/YT-Advanced#93]
![Screenshot_20230829_140658_ReVanced Manager.png](https://github.com/YT-Advanced/YT-Advanced/assets/91851160/ae60357b-24f6-4fd9-8bc5-1712ce8cef86)

-Can't share the log because I can't upload it to GitHub

**Comment by YT-Advanced** [comment]
Try again right now
