### ISSUE TITLE
Can you solve this tablet issue?

### ISSUE THREAD

**Issue by girshcatt** [YT-Advanced/YT-Advanced#94]
https://github.com/ReVanced/revanced-patches/issues/2606 Because of this on tablets with yt versions above 18.20.39 we cant use old quality menu and custom speed, this issue was mostly ignored by revanced, but can you adapt old quality patch for tablets? I can explain why i dont want to just spoof the version: because in future 90% of patches will target new versions, and already 18.20.39 start to getting old and have some issues. 1 solution - adapt old quality settings patch for tablets; 2 solution add quality choice button to overlay buttons, speed overlay button already exist

**Comment by YT-Advanced** [comment]
Since this issues occured because tablet and phone use different layout, I don't think I can solve it. But you can spoof app version to `v18.20.39` and all will work as excepted

**Comment by girshcatt** [comment]
But can you anyway add quality button to overlay buttons? Because i want to use new yt versions just with speed and quality overlay buttons, this will be enough for me

**Comment by YT-Advanced** [comment]
what, quality overlay button ? I think it is not neccessary at all

**Comment by girshcatt** [comment]
ok(
