### ISSUE TITLE
Quick actions container not showing

### ISSUE THREAD

**Issue by Kiwikip** [YT-Advanced/YT-Advanced#95]
None of the buttons are visible except for the share button. Hiding, unhiding and restarting doesn't help. I've tried on difirent versions but doesn't help. ![Screenshot_20230829_182525_ReVanced Extended.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/130678837/00778096-3fec-4f5b-b5e3-a763c21cd0dc)

![Screenshot_20230829_182509_ReVanced Extended.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/130678837/16f630ae-9527-4f9d-ad83-f26aefc94ab5)

![Screenshot_20230829_182430_ReVanced Extended.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/130678837/40a3e70a-8c79-4cae-b9c2-ae037e6a4515)

![Screenshot_20230829_182528_ReVanced Extended.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/130678837/67b52d79-2bfb-4b46-ac71-61334217584f)

![Screenshot_20230829_182537_ReVanced Extended.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/130678837/b82ed21a-3008-4eef-87da-0058d34f99cb)

**Comment by YT-Advanced** [comment]
First, can you repatch and reinstall, then turn off all option ? It is worked normally in my device. And also if u can ib me via Telegram

**Comment by Kiwikip** [comment]
The fault was an old settings file
