### ISSUE TITLE
Questions regarding Crowdin

### ISSUE THREAD

**Issue by odkate** [YT-Advanced/YT-Advanced#96]
Hello
Why did you give a link to Crowdin in Telegram, but I received an invitation to Crowdin Enterprise in my mail? 
Where is the right place to translate?

**Comment by YT-Advanced** [comment]
It is a bug when I transfer my project. The correct project is what I send in Telegram

**Comment by odkate** [comment]
> send in Telegram

Then make me an proofreader there

**Comment by YT-Advanced** [comment]
> > send in Telegram
> 
> Then make me an proofreader there

Can u check
