### ISSUE TITLE
Copying to revanced.apk hangs/fails (Termux rvx-builder)

### ISSUE THREAD

**Issue by lowestprime** [YT-Advanced/YT-Advanced#97]
Everything perfect now, except hangs at final step: "Copying to revanced.apk" 😥 Maybe it's a Termux storage permission issue? Any idea how to fix? Already tested default and j-hc revanced-clis, and rvx-builder still gets stuck at this step. Also, tested a clean Termux and rvx-builder reinstall, which also failed to fix the issue. 

![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/eb6c842f-8a7c-46da-b4c5-e16f0db5a11a)

_Originally posted by @lowestprime in https://github.com/YT-Advanced/YT-Advanced/issues/85#issuecomment-1698058220_

**Comment by lowestprime** [comment]
Fixed! So fast too. Thank you!! 🤘

**Comment by lowestprime** [comment]
Spoke too soon:

Downloading YouTube apk is very slow now (2+ min), same wifi speed used:

![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/2c5ccb7d-cdda-437d-863e-8678e463da06)

But more importantly, the exported YouTube apk appears to be corrupted:

![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/51a77306-61e2-4a85-91e1-65475e02c3ce)

**Comment by YT-Advanced** [comment]
Seem like the apk is not signed 🤔

**Comment by lowestprime** [comment]
Yep still fails despite "./rvx-builder.sh reinstall --delete-keystore"

![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/d5dcc4d6-931d-4f78-ab8b-12e8b043db60)

![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/dd62cb33-86ea-46cc-85c3-c80716962b3a)
