### ISSUE TITLE
Language switch patch not present

### ISSUE THREAD

**Issue by Kuddus73** [YT-Advanced/YT-Advanced#98]
In the latest update even if I include the patch to change the language in app, the patch is not present in the app.
![Screenshot_20230830_063714_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/127908708/9c507127-f71f-43d8-aa48-919071ac76ab)
![Screenshot_20230830_063600_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/127908708/fa9371f7-7748-4a29-b7aa-f4fd0dd92f65)

**Comment by YT-Advanced** [comment]
How about the RVX Setting 🤔

**Comment by Kuddus73** [comment]
> How about the RVX Setting 🤔

Since inotia added this patch it was always in General.

Screenshot from patch v2.188.2:
![Screenshot_20230830_070419_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/127908708/5cadc652-e684-4fa1-9191-6fbf803ed3dc)

**Comment by YT-Advanced** [comment]
I'm too busy and forgot to notify that it have been solved
