### ISSUE TITLE
Filmstrip overlay isn't working on v18.33.40

### ISSUE THREAD

**Issue by selfmusing** [YT-Advanced/YT-Advanced#99]
I've patches v18.33.40 via Revancify , but the filmstrip overlay isn't working. (  Disable Hide Film strip overlay from rvx settings - already disabled )
Here is Patchlog : 
[patch_log.txt](https://github.com/YT-Advanced/YT-Advanced/files/12472183/patch_log.txt)

Video of that bug : 

https://github.com/YT-Advanced/YT-Advanced/assets/109387456/ae3a021a-2b72-4d2e-b867-b3d617b84b43

Debug Logs : 
[logs-2023-08-30-11-28-09.zip](https://github.com/YT-Advanced/YT-Advanced/files/12472187/logs-2023-08-30-11-28-09.zip)

**Comment by Kantotero** [comment]
How were you able to have a seek thumbnail preview? Do you enable `spoof player parameters` patch?

**Comment by selfmusing** [comment]
Nah , i don't add spoof player parameters patch ( Benefits of using Core Patch on a Rooted Device :)


https://www.reddit.com/r/revancedextended/comments/15nmlcl/any_video_i_play_suddenly_starts_buffering_and/jvq642r ( READ )

**Comment by YT-Advanced** [comment]
I love u so I fixed it

**Comment by selfmusing** [comment]
Damn!! 😳💖

**Comment by Kantotero** [comment]
> I love u so I fixed it

Seems tobe working fine now for latest ver too (for non-root)..👀

**Comment by devilboy1122** [comment]
![Screenshot_2023-09-05-01-09-42-881_app rvx android youtube-edit](https://github.com/YT-Advanced/YT-Advanced/assets/79780868/9f9d3813-626f-4e5b-a6ec-1e6dcb9282e6)
 when search video then video three dot show remix option please hide this option

**Comment by YT-Advanced** [comment]
> ![Screenshot_2023-09-05-01-09-42-881_app rvx android youtube-edit](https://github.com/YT-Advanced/YT-Advanced/assets/79780868/9f9d3813-626f-4e5b-a6ec-1e6dcb9282e6)
>  when search video then video three dot show remix option please hide this option 

Create new issues

**Comment by MrNorthernLights** [comment]
> ![Screenshot_2023-09-05-01-09-42-881_app rvx android youtube-edit](https://user-images.githubusercontent.com/79780868/265529433-9f9d3813-626f-4e5b-a6ec-1e6dcb9282e6.jpg) when search video then video three dot show remix option please hide this option

RVX settings > Flyout menu > Edit (Add Remix line in the menu and restart).
